src/my_app/__init__.py
from flask import Flask, url_for, redirect, flash
import os

app = Flask(__name__, instance_relative_config=True)
app.config['SECRET_KEY'] = os.urandom(6) or 'you-will-never-guess'



from .views import hello, login, sum

app.register_blueprint(hello.hello_bp)
app.register_blueprint(login.login_bp)
app.register_blueprint(sum.sum_bp)

@app.route('/')
def index():
    return redirect(url_for('hello.hello_world'))

src/my_app/views/hello.py
from flask import session, Blueprint, render_template

hello_bp = Blueprint('hello', __name__, url_prefix='/hello')

@hello_bp.route('/')
def hello_world():
    if 'user' in session:
        return render_template('home.html', name=session['user'])
    return render_template('home.html')

@hello_bp.route('/hi')
def hello():
    if 'user' in session:
        return render_template('hello.html', name=session['user'])
    return render_template('hello.html')

src/my_app/views/login.py
from flask import Blueprint, redirect, request, session, url_for

login_bp = Blueprint('login', __name__, url_prefix='/login')

@login_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return '''
                    <form method="post">
                        <input type="text" name="user">
                        <input type="submit" value="login">
                    </form>
               '''
    if request.method == 'POST':
        session['user'] = request.form['user']
        return redirect(url_for('hello.hello_world'))

src/my_app/views/sum.py
from flask import Blueprint

sum_bp = Blueprint('sum', __name__, url_prefix='/sum')

@sum_bp.route('/<int:num1>/<int:num2>')
def sum(num1, num2):
    return str(num1 + num2)

src/my_app/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    Hello {{ name }}!
</div>
</body>
</html>

src/my_app/templates/home.html
<!--
{% include "homePrima.html" %}
Funciona igual que el include_once de php
-->

{% if name %}
    <h1>Hi {{ name }}</h1>
{% endif %}
<h1>Welcome to our WebApp</h1>
<a href="{{url_for('login.login')}}">Login</a>

src/my_app/templates/homePrima.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HELLO PRIMA</title>
</head>